source 'https://rubygems.org'

# Specify your gem's dependencies in emmy-engine.gemspec
gemspec

gem 'eventmachine', '~> 1.0.7'

gem 'emmy-http', path: '~/Dropbox/Projects/emmy/emmy-http'
gem 'emmy-http-server', path: '~/Dropbox/Projects/emmy-http-server'
